train_csv: "./data/ada_usdt_15m_train.csv"
save_dir: "./models/ada_tr_2"
run_name: "ada_run_5"
# for extra training:
load_model: "./models/ada_tr_2/final_model.zip"  # path to previous model
resume_tensorboard_log: "./models/ada_tr_2/tensorboard/ada_run_5"  # same tensorboard folder
#------
total_timesteps: 200000
n_steps: 128
batch_size: 64
n_epochs: 4
gamma: 0.99
gae_lambda: 0.95
learning_rate: 3e-5
ent_coef: 0.01
vf_coef: 0.5
clip_range: 0.2
max_grad_norm: 0.5
lstm_hidden_size: 256
n_lstm_layers: 1
shared_lstm: true
enable_critic_lstm: false
net_arch:
  pi: [128, 128]
  vf: [128, 128]
  lstm: [256]
log_freq: 500
initial_amount: 1000.0
hmax: 500
transaction_cost_pct: 0.001
reward_scaling: 1.0
